server:
  port: 8081
spring:
  cloud:
    function:
      definition: myConsumer
    stream:
      bindings:
        myConsumer-in-0:
          destination: 'object/match'
          group: nonexclusive
          consumer:
            concurrency: 5
      binders:
        solace-cloud:
          type: solace
          environment:
            solace:
              java:
                clientUsername: solace-cloud-client
                clientPassword: pswd
                host: host
                msgVpn: gvpn
  jpa:
      hibernate:
        ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/seekAndFindDb?useSSL=false #only for testing/dev purposes we disable ssl ...
    username: seekAndFind
    password: GJW9

  sql:
    init:
      mode: always
