server.port = 8080

logging.level.com.gjw9.server=INFO
logging.level.org.hibernate=ERROR

#db propreties
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.sql.init.mode=always 

#solace propreties
spring.cloud.function.definition=weAppConsumer

spring.cloud.stream.bindings.weAppConsumer-in-0.destination=object/match
spring.cloud.stream.bindings.weAppConsumer-in-0.group=exclusive
spring.cloud.stream.bindings.weAppConsumer-in-0.consumer.concurrency=5

spring.cloud.stream.binders.solace-cloud.type=solace
spring.cloud.stream.binders.solace-cloud.environment.solace.java.clientUsername=solace-cloud-client
spring.cloud.stream.binders.solace-cloud.environment.solace.java.clientPassword=hpouss5kmb90hci72sf5qen4i
spring.cloud.stream.binders.solace-cloud.environment.solace.java.host=tcps://mr-connection-xpgc9z4f1yv.messaging.solace.cloud:55443
spring.cloud.stream.binders.solace-cloud.environment.solace.java.msgVpn=gjw9

#email propreties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gjw9seekandfind@gmail.com
spring.mail.password=ytwm lpab irwl sdxv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


