// package com.gjw9.server.api;

// import org.springframework.beans.factory.annotation.Autowired;
// import org.springframework.web.bind.annotation.*;

// import com.gjw9.server.infra.UserProfile;
// import com.gjw9.server.infra.UserRepository;
// // This means that this class is a RestController
// @RestController
// // This means URL's start with /demo (after Application path)
// @RequestMapping(path = "/profiles")
// public class UserProfileController {
//     // This means to get the bean called userRepository
//     // which is auto-generated by Spring, we will use it to handle the data
//     @Autowired
//     private UserRepository userRepository;

//     // Map ONLY POST Requests
//     @PostMapping(path = "/add")
//     public @ResponseBody UserProfile addNewUser(@RequestParam String json) {
        

//         UserProfile springUser = new UserProfile("hehe", "d", "d", "s");
//         // userRepository.save(springUser);
//         return springUser;
//     }

//     @GetMapping(path = "/all")
//     public @ResponseBody Iterable<UserProfile> getAllUsers() {
//         // This returns a JSON or XML with the users
//         return userRepository.findAll();
//     }

// }
