services:

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - 8080:8080
    depends_on :
      db:
        condition: service_healthy
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/seekAndFindDb
      SPRING_DATASOURCE_USERNAME: seekAndFind
      SPRING_DATASOURCE_PASSWORD: GJW9
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend

  db:
   image: mysql:latest
   environment:
     MYSQL_DATABASE: seekAndFindDb
     MYSQL_USER: seekAndFind
     MYSQL_PASSWORD: GJW9
     MYSQL_ROOT_PASSWORD: GJW9
   ports:
     - 3306:3306
   volumes:
     - seek-and-find-db-volume:/var/lib/mysql
   networks:
     - backend
   healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  client:
   build:
     context: ./client
     dockerfile: Dockerfile
   container_name: client
   depends_on:
     - server
   ports:
     - 3000:3000
   volumes:
     - ./client:/app
     - /app/node_modules
   environment:
     - VITE_APP_BACKEND_ADDRESS=http://localhost:8080
   networks:
     - frontend

volumes:
 seek-and-find-db-volume:

networks:
 backend:
 frontend:
